profile:
    # dataset: fitbit_bhp_simula_combined_v1
    # dataset: simula_fitbit_data_v1
    # dataset: bhp_fitbit_data_v1
    # dataset: bhp_fitbit_data_v2
    # dataset: bhp_fitbit_data_v4
  # dataset: bhp_fitbit_data_v7
  # dataset: bhp_fitbit_data_v8_val
  dataset: bhp_fitbit_data_v8_val_stratified
    # dataset: bhp_test
    # dataset: bhp_fas_input

clean:
    # target: fas_category
  target: fas
  classification: false
  onehot_encode_target: false
  combine_files: True
  percentage_zeros_threshold: 1.0
  correlation_metric: pearson
  input_max_correlation_threshold: 1.0

featurize:
    # If empty, all input variables are used
  variables_to_include:
  - age
  - heart_rate_bpm_min
  - bmi
  - resting_heart_rate
  - heart_rate_bpm_mean
  - levels.summary.light.minutes
  - weight
  - sedentary_minutes
        # Negative correlation:
  - gender
  - height
  - very_active_minutes
    # Extra for validation group:
  # - distance_range
  # - distance_max
  # - heart_rate_bpm_range
  # - very_active_minutes
  # - levels.summary.wake.thirtyDayAvgMinutes
  # - levels.summary.light.thirtyDayAvgMinutes
  # - minutesAsleep
    #
        # Extra stuff
        # - levels.summary.rem.count
        # - calories
        # - heart_rate_bpm_std
        # - lightly_active_minutes
        # - bmr
        # - distance
        # - deep_sleep_in_minutes
        # - levels.summary.rem.minutes
        # - steps

        # - bmr
        # - steps 

        # - heart_rate_bpm_min
        # - heart_rate_bpm_mean
        # - weight
        # - sedentary_minutes
        # - resting_heart_rate
        # - bmr
        # STOP
        # - very_active_minutes
        # - steps
        # STOP
        # - bmi
        # - levels.summary.wake.count
        # - levels.summary.light.count
        # - height
        # - very_active_minutes
        # - steps
        # - distance
        # - lightly_active_minutes
        # - efficiency

        # - deep_sleep_in_minutes
        # - resting_heart_rate
        # - calories_max
        # - calories_min
        # - distance_mean
        # - distance_max
        # - steps
        # - age
        # - gender
        # - height
        # - STRESS_SCORE
        # - fas_2
        # - overall_score
        # - composition_score
        # - revitalization_score
        # - duration_score
        # - deep_sleep_in_minutes
        # - resting_heart_rate
        # - restlessness
        # - calories_max
        # - calories_min
        # - distance_mean
        # - distance_max
        # - heart_rate_bpm_min
        # - heart_rate_bpm_mean
        # - steps
        # - age
        # - gender
        # # - height
        # - weight
        # # - bmi
        # - sedentary_minutes
        # - minutesAsleep

    # By setting this to True, the add_-options below are overrided.
  use_all_engineered_features_on_all_variables: false

    # List the variables below each add_* to add engineered feature
  add_sum:
        # - variable1
  add_gradient:
        # - variable1
  add_mean:
        # - variable1
  add_maximum:
        # - variable1
  add_minimum:
        # - variable1
  add_min_max_range:
        # - variable1
  add_slope:
        # - variable1
  add_slope_sin:
        # - variable1
  add_slope_cos:
        # - variable1
  add_standard_deviation:
        # - variable1
  add_variance:
        # - variable1
  add_peak_frequency:
        # - variable1
  rolling_window_size_sum: 3
  rolling_window_size_mean: 3
  rolling_window_size_max_min: 3
  rolling_window_size_standard_deviation: 3

    # List features here to remove the raw variables after engineering features
    # from them
  remove_features:
        # - variable1
  - logId
  - rmssd
  - high_frequency
  - low_frequency
  - coverage
  - levels.summary.restless.count
  - levels.summary.restless.minutes
  - levels.summary.awake.count
  - levels.summary.awake.minutes
  - levels.summary.asleep.minutes
  target_min_correlation_threshold: 0.0

split:
  train_split: 0.6
  shuffle_files: False
  calibrate_split: 0.0
  shuffle_samples_before_split: False

scale:
  input: minmax
  output:
    # output: log

sequentialize:
  window_size: 7
  overlap: 6
  target_size: 1
  shuffle_samples: true
  future_predict: false

train:
  learning_method: dnn_simple
  n_epochs: 1000
  batch_size: 256
  kernel_size: 2
  early_stopping: True
  patience: 200
  weigh_samples: true
  weight_min_threshold: 28
  weight_max_threshold: 50
  weight: 3.5
  hyperparameter_tuning: false

evaluate:
  show_inputs: True
