profile:
    # dataset: bhp_v1
    dataset: bhp_fitbit_data_v8_val_stratified

clean:
    # target: fas_category
  target: fas
  classification: false
  onehot_encode_target: false
  combine_files: False
  percentage_zeros_threshold: 1.0
  correlation_metric: pearson
  input_max_correlation_threshold: 1.0

featurize:
    # If empty, all input variables are used
  variables_to_include:
  - age
  - heart_rate_bpm_min
  - bmi
  - resting_heart_rate
  - heart_rate_bpm_mean
  - levels.summary.light.minutes
  - weight
  - sedentary_minutes
  # Negative correlation:
  - gender
  - height
  - very_active_minutes

    # By setting this to True, the add_-options below are overrided.
  use_all_engineered_features_on_all_variables: false

    # List the variables below each add_* to add engineered feature
  add_sum:
        # - variable1
  add_gradient:
        # - variable1
  add_mean:
        # - variable1
  add_maximum:
        # - variable1
  add_minimum:
        # - variable1
  add_min_max_range:
        # - variable1
  add_slope:
        # - variable1
  add_slope_sin:
        # - variable1
  add_slope_cos:
        # - variable1
  add_standard_deviation:
        # - variable1
  add_variance:
        # - variable1
  add_peak_frequency:
        # - variable1
  rolling_window_size_sum: 3
  rolling_window_size_mean: 3
  rolling_window_size_max_min: 3
  rolling_window_size_standard_deviation: 3

    # List features here to remove the raw variables after engineering features
    # from them
  remove_features:
    - logId
    - rmssd
    - high_frequency
    - low_frequency
    - coverage
    - levels.summary.restless.count
    - levels.summary.restless.minutes
    - levels.summary.awake.count
    - levels.summary.awake.minutes
    - levels.summary.asleep.minutes
  target_min_correlation_threshold: 0.0

split:
  train_split: 0.6
  shuffle_files: False
  calibrate_split: 0.0
  shuffle_samples_before_split: False

scale:
  input: minmax
  output:

sequentialize:
  window_size: 5
  overlap: 4
  target_size: 1
  shuffle_samples: true
  future_predict: false

train:
  learning_method: dnn_simple
  n_epochs: 1000
  batch_size: 256
  kernel_size: 2
  early_stopping: True
  patience: 200
  weigh_samples: true
  weight_min_threshold: 28
  weight_max_threshold: 50
  weight: 3.5
  hyperparameter_tuning: false

evaluate:
  show_inputs: True
