profile:
    dataset: name_of_dataset

clean:
    target: name_of_target_variable
    classification: False
    onehot_encode_target: False
    combine_files: False
    percentage_zeros_threshold: 1.0
    correlation_metric: pearson
    input_max_correlation_threshold: 1.0

featurize:
    # If empty, all input variables are used
    variables_to_include:
        # - variable1
        # - variable2

    # By setting this to True, the add_-options below are overrided.
    use_all_engineered_features_on_all_variables: False

    # List the variables below each add_* to add engineered feature
    add_sum:
        # - variable1
    add_gradient:
        # - variable1
    add_mean:
        # - variable1
    add_maximum:
        # - variable1
    add_minimum:
        # - variable1
    add_min_max_range:
        # - variable1
    add_slope:
        # - variable1
    add_slope_sin:
        # - variable1
    add_slope_cos:
        # - variable1
    add_standard_deviation:
        # - variable1
    add_variance:
        # - variable1
    add_peak_frequency:
        # - variable1
    rolling_window_size_sum: 10
    rolling_window_size_mean: 10
    rolling_window_size_max_min: 10
    rolling_window_size_standard_deviation: 10

    # List features here to remove the raw variables after engineering features
    # from them
    remove_features:
        # - variable1
    target_min_correlation_threshold: 0.0

split:
    train_split: 0.5
    shuffle_files: False
    calibrate_split: 0.0

scale:
    input: minmax
    output:

sequentialize:
    window_size: 5
    overlap: 0
    target_size: 1
    shuffle_samples: False
    future_predict: False

train:
    learning_method: dnn
    n_epochs: 10
    batch_size: 256
    kernel_size: 5
    early_stopping: True
    patience: 20

evaluate:
    show_inputs: True
